name: Deploy NexusBridge to TON Testnet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Blueprint
      run: npm i -g @ton-community/blueprint @ton/core

    - name: Import Testnet Key
      env:
        TON_TESTNET_MNEMONIC: ${{ secrets.TON_TESTNET_MNEMONIC }}
      run: |
        mkdir -p ~/.config/blueprint
        echo "$TON_TESTNET_MNEMONIC" | blueprint keys import --network testnet --stdin

    - name: Build Contract
      run: blueprint build

    - name: Deploy NexusBridge
      env:
        ADMIN: ${{ secrets.TON_TESTNET_ADMIN }}
      run: |
        sed -i 's#Address.parse("YOUR_TESTNET_WALLET_ADDRESS")#Address.parse("'"$ADMIN"'")#' scripts/deployNexus.ts
        blueprint run scripts/deployNexus.ts --network testnet
